using System;
using System.Linq;
using UnityEngine;
using UnityEngine.Assertions;
using UnityEngine.XR.WSA.WebCam;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.Networking;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Collections.Specialized;
using SimpleJSON;

/// <summary>
/// Manages taking and saving photos.
/// </summary>
public class PhotoManager : MonoBehaviour
{
    /// <summary>
    /// Displays status information of the camera.
    /// </summary>
    public TextMesh Info;

    /// <summary>
    /// Whether or not to show holograms in the photo.
    /// </summary>
    public bool ShowHolograms = true;

    /// <summary>
    /// Whether or not to start the camera immediatly.
    /// </summary>
    public bool AutoStart = true;

    /// <summary>
    /// Actual camera instance.
    /// </summary>
    private PhotoCapture capture;

    /// <summary>
    /// True, if the camera is ready to take photos.
    /// </summary>
    private bool isReady = false;

    /// <summary>
    /// The path to the image in the applications local folder.
    /// </summary>
    private string currentImagePath;

    /// <summary>
    /// The path to the users picture folder.
    /// </summary>
    private string pictureFolderPath;

    private bool found = false;

    private Camera playerCamera;

    [SerializeField]
    private GameObject resObject;

    public Image experienceMeter;
    public Image skillsMeter;

    private void Start()
    {
        Assert.IsNotNull(Info, "The PhotoManager requires a text mesh.");
        playerCamera = GetComponentInChildren<Camera>();

        Info.text = "Camera off";

        if (AutoStart)
            StartCamera();

#if NETFX_CORE
        GetPicturesFolderAsync();
#endif

    }

    /// <summary>
    /// Starts the photo mode.
    /// </summary>
    public void StartCamera()
    {
        if (isReady)
        {
            Debug.Log("Camera is already running.");
            return;
        }

        PhotoCapture.CreateAsync(ShowHolograms, OnPhotoCaptureCreated);
    }


    ///<summary>
    ///Keep calling take_photo till we get a response
    ///</summary> 

    public void startCapturing()
    {
        StartCoroutine(TakePhotos());
    }

    public IEnumerator TakePhotos()
    {

        int i = 0;
        while (i < 3)
        {
            StartCamera();
            while (!isReady)
                yield return new WaitForSeconds(2);
            if (i == 2)
                found = true;
            TakePhoto();
            //yield return new WaitForSeconds(2.0f);
            i++;
            while (isReady)
                yield return new WaitForSeconds(2);
        }
        yield return new WaitForSeconds(1);
    }

    /// <summary>
    /// Take a photo and save it to a temporary application folder.
    /// </summary>
    public void TakePhoto()
    {
        if (isReady)
        {

            string file = string.Format(@"Image_{0:yyyy-MM-dd_hh-mm-ss-tt}.jpg", DateTime.Now);
            currentImagePath = System.IO.Path.Combine(Application.persistentDataPath, file);
            capture.TakePhotoAsync(currentImagePath, PhotoCaptureFileOutputFormat.JPG, OnCapturedPhotoToDisk);

        }
        else
        {
            Debug.LogWarning("The camera is not yet ready.");
        }
    }

    /// <summary>
    /// Stop the photo mode.
    /// </summary>
    public void StopCamera()
    {
        if (isReady)
        {
            capture.StopPhotoModeAsync(OnPhotoModeStopped);
        }
    }

#if NETFX_CORE

    private async void GetPicturesFolderAsync() 
    {
        Windows.Storage.StorageLibrary picturesStorage = await Windows.Storage.StorageLibrary.GetLibraryAsync(Windows.Storage.KnownLibraryId.Pictures);
        pictureFolderPath = picturesStorage.SaveFolder.Path;
    }

#endif

    private void OnPhotoCaptureCreated(PhotoCapture captureObject)
    {
        capture = captureObject;

        Resolution resolution = PhotoCapture.SupportedResolutions.OrderByDescending(res => res.width * res.height).Last();

        CameraParameters c = new CameraParameters(WebCamMode.PhotoMode);
        c.hologramOpacity = 1.0f;
        c.cameraResolutionWidth = resolution.width;
        c.cameraResolutionHeight = resolution.height;
        c.pixelFormat = CapturePixelFormat.BGRA32;

        capture.StartPhotoModeAsync(c, OnPhotoModeStarted);
    }

    private void OnPhotoModeStarted(PhotoCapture.PhotoCaptureResult result)
    {
        isReady = result.success;
        Info.text = isReady ? "Camera ready" : "Camera failed to start";
    }


    private void FillResultsUI()
    {
        /*GameObject skillsObject = GameObject.Find("Skills");
        GameObject parentObj = GameObject.Find("ResultObj");*/
    }

    private void OnCapturedPhotoToDisk(PhotoCapture.PhotoCaptureResult result)

    {
        if (result.success)
        {
            StartCoroutine(Upload());
            /*GameObject obj = GameObject.Find("Screen").GetComponent<TextMesh>;
            obj = "jhsvc";
            if(obj)
                obj.SetActive(true);*/

            //Node call & check if success
            //stop camera + display of json
            //
            //FillResultsUI();
            //StopCamera();
#if NETFX_CORE
            
            try 
            {
                if(pictureFolderPath != null)
                {
                    System.IO.File.Move(currentImagePath, System.IO.Path.Combine(pictureFolderPath, "Camera Roll", System.IO.Path.GetFileName(currentImagePath)));
                    Info.text = "Saved photo in camera roll";
                }
                else 
                {
                    Info.text = "Saved photo to temp";
                }
            } 
            catch(Exception e) 
            {
                Info.text = "Failed to move to camera roll";
                Debug.Log(e.Message);

            }
#else
            Info.text = "Saved photo";
            Debug.Log("Saved image at " + currentImagePath);
#endif

        }
        else
        {
            Info.text = "Failed to save photo";
            Debug.LogError(string.Format("Failed to save photo to disk ({0})", result.hResult));
        }



    }
    IEnumerator Upload()
    {
        /*List<IMultipartFormSection> formData = new List<IMultipartFormSection>();
        formData.Add(new MultipartFormDataSection("field1=foo&field2=bar"));
        formData.Add(new MultipartFormFileSection("file", currentImagePath));

        UnityWebRequest www = UnityWebRequest.Post("http://ar-divyata.us-west-1.elasticbeanstalk.com/data", formData);
        yield return www.SendWebRequest();

        if (www.isNetworkError || www.isHttpError)
        {
            Debug.Log(www.error);
            Debug.Log(www.responseCode);
        }
        else
        {
            Debug.Log("Form upload complete!");
        }*/

        /*byte[] img = File.ReadAllBytes(currentImagePath);

        //create multipart list
        List<IMultipartFormSection> requestData = new List<IMultipartFormSection>();

        requestData.Add(new MultipartFormFileSection("file", img, "Shivi.jpg", "image/jpg"));

        //WebRequest
        /*UnityWebRequest request = UnityWebRequest.Post("http://ar-divyata.us-west-1.elasticbeanstalk.com/data", requestData);
        request.SetRequestHeader("Content-Type", "multipart/form-data");*/
        //wr.chunkedTransfer = false;
        /*yield return wr.SendWebRequest();
        print("request completed with code: " + wr.responseCode);

        if (wr.isHttpError || wr.isNetworkError)
        {
            print("Error: " + wr.error);
        }
        else
        {
            print("Request Response: " + wr.downloadHandler.text);
        }


        /*WWWForm webForm = new WWWForm();
        // Change the image into a bytes array
        byte[] imageBytes = GetImageAsByteArray(currentImagePath);
        using (UnityWebRequest www =
            UnityWebRequest.Post("http://ar-divyata.us-west-1.elasticbeanstalk.com/data", webForm))
        {
            www.SetRequestHeader("Content-Type", "multipart/form-data");
            www.uploadHandler.contentType = "multipart/form-data";
            www.uploadHandler = new UploadHandlerRaw(imageBytes);
            www.downloadHandler = new DownloadHandlerBuffer();

            yield return www.SendWebRequest();
            if (www.isHttpError || www.isNetworkError)
            {
                Debug.Log("WWW Ok!: " + www.downloadHandler.text);
                print("Error: " + www.error+www.responseCode);
            }
            else
            {
                print("Request Response: " + www.downloadHandler.text);
            }
            string jsonResponse = www.downloadHandler.text;
       
        }*/

        WWWForm form = new WWWForm();
        string base64String = null;
        FileInfo fileInfo = new FileInfo(currentImagePath);
        // The byte[] to save the data in
        byte[] data = new byte[fileInfo.Length];

        // Load a filestream and put its content into the byte[]
        using (FileStream fs = fileInfo.OpenRead())
        {
            fs.Read(data, 0, data.Length);
        }
        //byte[] imageBytes = GetImageAsByteArray(currentImagePath);
        base64String = Convert.ToBase64String(data);
		//base64String = "/9j/4AAQSkZJRgABAQEAeAB4AAD/4RDcRXhpZgAATU0AKgAAAAgABAE7AAIAAAAGAAAISodpAAQAAAABAAAIUJydAAEAAAAMAAAQyOocAAcAAAgMAAAAPgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERocnV2AAAFkAMAAgAAABQAABCekAQAAgAAABQAABCykpEAAgAAAAM3MgAAkpIAAgAAAAM3MgAA6hwABwAACAwAAAiSAAAAABzqAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjAxODowOTowOCAxNzoxMDoyNQAyMDE4OjA5OjA4IDE3OjEwOjI1AAAARABoAHIAdQB2AAAA/+ELGGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSfvu78nIGlkPSdXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQnPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iPjxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFiIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iLz48cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0idXVpZDpmYWY1YmRkNS1iYTNkLTExZGEtYWQzMS1kMzNkNzUxODJmMWIiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyI+PHhtcDpDcmVhdGVEYXRlPjIwMTgtMDktMDhUMTc6MTA6MjUuNzIyPC94bXA6Q3JlYXRlRGF0ZT48L3JkZjpEZXNjcmlwdGlvbj48cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0idXVpZDpmYWY1YmRkNS1iYTNkLTExZGEtYWQzMS1kMzNkNzUxODJmMWIiIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyI+PGRjOmNyZWF0b3I+PHJkZjpTZXEgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj48cmRmOmxpPkRocnV2PC9yZGY6bGk+PC9yZGY6U2VxPg0KCQkJPC9kYzpjcmVhdG9yPjwvcmRmOkRlc2NyaXB0aW9uPjwvcmRmOlJERj48L3g6eG1wbWV0YT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgPD94cGFja2V0IGVuZD0ndyc/Pv/bAEMABwUFBgUEBwYFBggHBwgKEQsKCQkKFQ8QDBEYFRoZGBUYFxseJyEbHSUdFxgiLiIlKCkrLCsaIC8zLyoyJyorKv/bAEMBBwgICgkKFAsLFCocGBwqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKv/AABEIAf8BiAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APnk0UYoxWQCHikpxpKYCUZ9KOlFAAKWkpaQBRR2ooAKWkopgLRSZpc0AFFGaKAClpKKAFoNFFABRSUtACUUoooGFBoooAKO1FFIAooooAKQUtFMBKCaKQ0AIfeijrSUAJSUppKAGk4plOamVaEFFFFAhQamii38k4FRouWGKsomW2jpSbGMK5OFFddoi7dGgB/2v/QjXPxW+D0rptNG3T4h9f5mlF6jtZFqiiirEFFFFAHBlsUgDN9KdgHk9BTWnA4WsxAUPrzTNxHWkMxNMaQmnYCXcDSFxUOaBRYZPvHajf61FmlHPWiwEu4Gl61CDg09WNKwD6KTvRQAtAoo70AFLSUZpjFooopCFopKWgAo6UUUhhRQaMUwF7UlLQaQCUvagigUAGKPpRS0ANoNLSUAFNpaKYDTSUuKSkAlIaWmtTAYTk000p4pKsQUo60UqKWcAUAWYYj1Her0MW3qKbEmFH0qytZNmkUOA4rc0/8A48Y/x/maxcVtWH/HjH+P8zThuOexZooorUyCiiigDzsykjGaZmkopWAXNGaSimAtGaSigB2aUMKZRSsA/cPWlDAd6joosBOJF7ml8xPWq9FLlQFjzE9aPMT+9VeinYCwJU9aXzE/vVWopcoFnzE/vUvmp/eqrRRygWvNT+9R5qf3qq0UcoFrzU/vUecn96qtFHKgLfnR/wB6jzo/71VKKOUC35yf3qPOj/vVUoo5QLfnR/3qPOj/AL1VKKOUC550f979KPOj/vVToo5QLfnR/wB6jzY/71VKKOUC15qf3qTzU9arUUcoFnzE/vU0yL/eqCijlQE/mL60xmBNR0U7ALmjNJRTAXNTW7RrJlzioKKVgNVbqAf8tB+RqZL22HWUD8DWJRU8iKUmjfF/af8APYfka07TWdPjtUV7lQRnIwfX6VxtFNRSYOTZ3H9uab/z9L/3yf8ACj+3NN/5+l/75P8AhXD0VRJ3H9uab/z9L/3yf8KK4eigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKvHT9h+fdjsR3oSyjZgCX/So54k8yKNFaP9nRhsFnPpjFL/ZkY+87AfhS9pEd0ZtFaZ0yEH/WOPwpRpUf/PRs/hR7SIXRl0Vpf2bH/ef9KP7NjBGXfnij2kQuZtFaR02IMQWk460f2ZFn77D8qPaRDmRm0VoHTo8cOw+tOOmxDGWcZPtT9pEXMjNorT/syMkYZ+nfFJ/ZsW3Jdwc9KXtIhzIzaK1F0uInG9+ntQdLiGPmkwR7Ue0iHMjLorWGlQnnzHx+FL/ZMP8Az0kx+FHtIhzIyKK2P7HhPSSQ8e1INIhIyJJCv4Ue0iO5kUVsnRocjEr8npxTjokGDiV8jtxR7SIcyMSitoaNblf9ZJuz0yKVtEhXB8yTGcdRR7SIXRiUVt/2HBnmWQDOO2aedBg3Y8yXHqSP8KXtoBdGDRW82gQBuJZCMeoo/sK3wMSyE/h/hR7WLC5g0Vv/ANgQHpLIOec44/SlPh63BwZpPY8c0/aRC5z9FdAfD1uG/wBdJjPt/hS/8I9bk8TSfpR7SIznqK6H/hHrfPMso4z2/wAKUeHbZsYml9+n+FHtIiuc7RXRf8I7b95pe/p/hSjw5bHkTS4/D/Cj2kRnOUV0g8N2p/5by/p/hTf+EctskedL7dP8KPaRA52iuk/4Ru2AG6aXn6f4UL4ati+DNKPTp/hR7SIHN0V0v/CNW2cGaXPoMf4UHw3aj/ltN+n+FL2sRXRzVFdL/wAI1bcjzpc/h/hSf8I3a/8APeUD8P8ACj2sRnN0V0g8NWxBKzyHH0oPhu2B5mmx+H+FCqxYHN0V0o8NWpA/fy8/T/Ck/wCEbtgcGWX9P8KftIgc3RXSnwzbDrPL+n+FFL2sQLOyOVTtHIPTFVZbWLqOD71MrhSCnfnrTiFkBP3genvXNqYblDBTgjjPWnjbjac+vSrM1ufukHHaoFBU4PXPSi40Kqx926EUropU7Dkg0fLzgdabuKt8vJFAXG4JI2/e/lTghPJPOeBTRhuTQfmyO+eDTKB8cfeye9AGWALUYIU89KXALct+GKYg2Kw+Xhskc01UwuRk4PQ0/wCZiOAR6jtQFU5APz0CGNw3JzxwDSgHYSx6mkxnkkEj1p23gcn60ALjAz2HH1o6jp9MUwHO7d0J4peBjA57CkOwoxv9Vxing9QeD2pGDAZ4HvSjpljkmgaHLuyQTgdaVGxIc8AGkx328ketKeQQvU85oKHgkrgn5qVPmBHf0pqnbyx4xS8eYDntjIoELyBwOhpcgngfdOcetGcfyxSJnOf0oAkXByT696TJCkN6/nTBt6k8HilzjgnOPapsBNnPXGQOKFbqOOnAphJ3ZT05pQCoGRyRmjYYvzOxJbAxxij7xyDnIwQaOo3AcdaeOB79adwsA+8QcHH8qf19MYqIKT0yOaUHOMDvQXYUkFh1JpynPGSBTWbHOMUZAII570wsScFV9+opytlSG6g8VFnOPT2qQevUUiR2e1O61Fg5zTg21uemKYDz6cfjRgEDHPNNByfmwPSkP3ueAemKhsGOLc9OTS4G0nP1FNz3JPHFBPzEd/6VLuyR2cd80hPy8EDnGKAQpHHHtSYyx7c00UGTghevTNPb51FRRjG7PJp6HsMZx0oWgwVs8dQTSbwJOuB2FNLZwMcd8d6UDqBg+3pVjAMxHzcc0U0DLYI+pNFSwMm2bblJD+OK04IlwFbGR0OazV++JB0Y447VeiBK5Tr0JpyMEixIo2sBzz1qhMpWTNXQ21gWPHt3qO6i3ruP147VnbXQpFF8hgU6dSMUw9yQPXPpU0u4fN2xTdgVRu5HU1pFiIx87MT0xkCk27lz0Pp2py5ZsnpnpS+o6CqKQ3blsdTjJx3FOVQq579QD2FAUemeOopwUAgUyWMAIySRz0FIeAMHmpMcN35phGVAXHXNIVhnXBQd+fejGc8+4p4X5tjHANJnIIAwBx9aBjQCT8v5Up5kA6EUIORnr7mpQA3A9fSkMYR0IHem/wAW4evANTFOvzcdADTWU8diO9ACFcdDk/ypd3ygY696Xae3I60Fdvp06CpuO4AkgDtnHPanKeWXp70052//AF6XkgHHOOfencB+AxHQEfrS7gPmI/Ko925uwHvTgMHrmmFh7LngDrzSDlc59qCQABkg+lLwMAZ60N2GKGOcYAHSne/JA4prcN0yMjkUuD83Py9agB69DzwBwKXJG1Wx7Ypg5XjH5UHquKaDUlJ4GT78UFgpGR1powPwHFBG5RuJHHBpopClvmPv0pBwcim4+XDdfWn5I2gEDNDYx4GMe55pc5XJPGcU0Y5HvxRuIbA6elSm2IcV3Ie4pFOeowMY5pSccg8UgXr830pxfQB6naoBIbtSnngDp0qMHLAL8vGaUcAbup5FS9wHMWIx19aFwcjqSOvpS55HbIpA23njr600AEHaNvahydvPc9aFPB4/+vSgjgGpAAe2OR0oJ6kDB7mmuSGx75zR97knaP50wDIYdDilIO7gHpSMu4fN17UoG3G49BRcAHoQSKKdwPUZH50VW4Ga0BVIQ3ylRnArQWMLGpGenNYsF4z3GJjntzWyLlDGADzjjNDVjndxAdhwFznpRIxMfPPb6UoKlyF5I9KiOVVie3akUiu3C9N2aiIJxj7vQj0qbcoGFOOajzzkDrxTGNKHBC4yvNCkswBHUZ5oGcEY59aRlLEbTjjFFxgynPB68gUvLY7Cl2dyRxx9Keq4XOee1O6AiBKsVxwe9OACE56Yx9aUg7PxpFjZgOc85ouAgG7rx6GjyyXPIA7VJ5ecikCnbjJOD6UXQDFUE/LjFKcds57VJ5ajk8mmqg35x9Pai/YQbCzL831pxC8qenOacQNh9jTcbu2fepY0MIKDg0hGeR1p5CsuO4/WmBiAWA46c0gGnj5W5PUYp0Z5K4pVJDDAz2oxnO31zT6DAIA+T8xHJNG7kknPOcUu4beeOeaQqGOfXpiquO45SQVwMgnGaANr5zx2z2pG+XGeuenpTiTjBGam4D/XHApQQuAcke1Rrhj6GnFuwPU8UgF3Z+VRg5607FNBI7Y9aGY9R09KaZVx3DYGeaRSSCD0zSYA/h560Dh8DJ5oYDgfm2jk07p25zxQjc8DvR91iM9+tJMY4HHORg0EhffnrTQcgjOO44p24nbjkd6FdCHDhs9u9BGR9DSA/Ng8qaP4W3degrVMBXbOGA5NOzlee3emEgcHgU7OG7FSORWcrNgGTvUdQfWlIJUggdeMCm7sN97oKASee45xUgPyM/L2ppPX60mec9iOlKffsOlVYBzHKjPX2pu84K4Ax0zSgfKOeaTOQQeTmiwDh8yjP403OOOoobOTz25obquD2yKtRADkEFTnnpiijk8k8CinYVzmVb8/Y9KnW5deVbIx0Nab+C9RaNpbBvtCryVxhsVz8rSQSFJUKMpwVbjFarln8I2mtGaceosCM9+uKla7aSFgpxzWOkuWzirCy/KVx1pOFmZNF/zQMkcnNOSQbMZOeoqjG7eYcHHHSrMb7QM5wTjFZtAThgQMHJzT1GGIOAO1QsMNlc7R39KlQ8cjOec1DRWw8AbSOvrTQCq9NwpVyeM4NP2/l7VACBtqgMppS2MA0gJIPqKXbxyc0rgKVwcnimlugDY5pwKkfMCR2pSvYdacfMQzGR8uaCnP0pwG4YHGO1O3Dbnv0xTvZjaGkfL60AHjHGeDTido5+mKNowAOaHIOWw3Zg44prLxgipQNpORmkJzwcfSlcCMx7MfTNAPynjinAfLz64FDAqcMOhoTAjaMhhjnPtRwBnOARyKezgnqRg03IzjHAFO47Dc4I7g8ZoOT1OO1KxOBjkCkC5+83XqMUDSFDc849KkIBTB/AUwr6L+NLuwBn6VWwxf4cdOaXPYDOOpoz8xBXtSEjvxx2pJWEIjElupwOtLna2R1PJoWRcED/8AXQM8cDFJjBSRlffNPJwuO3ekzgcYJ6GlB5IbgjnHrSBoXPIA54wcUBsdByOAKapw2O2cing4Y54z3p7jEz3P4UpJxkjmmk9gOAfzpQcnJ61VgHN0yeRRuKkd/U0igZA+tAGOM4GfSptYQ7g9MYz0pQTyTz2poI3H/CgqQv1PpTSAcRyOelKw6YJ+tJnb0GfWkznucdqsBwO04P3QM0oIzx3pnJYY6elJ90nmgViQ5OOfr70jf1pqnHX9aXcd2CeKY7BweAfqKKM9WHGeDRQTY721lFlonmRypvcEbO9eYeKpUa+2Lgv1c+/pXVahqC2tnLKxGUX5V9688mmM07yv1c55Nc+Cpu/MddeS2RCDg8+tPEnzcEim4DHrim8AcHnNena5yWL0Um7G3g+9WVcBgSCO341lq+0A+hroNOsFuoVkdy27oM9Kxmrak2I42AypP/1zTkJ3bSOcYro4NCsHAZ0YsVxnd0pJ/DsSYMDHHSsJMowg3IIGO3PenY4wDirc2lzxKcdAeKq7ZIyfNH41mKw5WAXaelG3gYOOaaGHseKc3ygDPvUgGfvH0oBGMsDg9aF4zxwRmjBKHIy31qkAu5lBI5GaVuT90nucUhIKDAwfSjoAQTnpVbliggjJOBSqdgwRg54ppGByOM81Js3YJ7etSL1I8jdk53fWnBeRx16UnA5J709RjJB4oHZDRgZDDB7H1pcF2BPQ8GkK78ZPHalIAIPpTQCMqgAeopnl5JGR0xT85zngUgTDD0pCY2RcKAnAA5FRg7h8oqwwAyM9scVEEXp04/OmnqO9iM9QM4zTsdj0pXAyMfiaaBuUc4brVc1wAyDaTyewpVYsuD6U0KPm29/WkUlWx36GlfQY843qB2HX1p4OOR2ph/hwM47UrYKjGeT61IMOMnAIB7e9OVmyfpjn1pM5U8/jSBjjjk4oAeOuSecc+1KDnjGee9MDZUYHQ07qD655FC0AUHCk+/SlGeegz2pFIBHYUH7vPHOMitOa4D04XpTe4OaC21c5yKCcjNMBQP16U4/N04xTR97px2FKc5K9DSYCp70g6gdfSkJIBJ4obnnGKAFU4J46UpU8H1FIDjinE/Jmi4DM4PNKfyo25AzjilI9uKOYLCYODyKKcANw+lFK4jK1y+NzcCHPyJ1HqaxiRtxjoOtLIS0jMx560iR72Cr1Y8/SuunBQikhybbFVPLtWd+rHC1F9alncNJhCSi8LUZXgZrQkFYhce9dZ4YxJZgHgqx/GuSxxXeeHLPy9PgyuGb5j+NY1rcthM3raPOD2q75AXqMg0+GJQg4OadIflXB6GuN+RqloVZIhtIIGKry6bC8ZJUZPXiryg8gjIbnmpETIweRSHY5e70NTl4hzjisp7WaA4YZPY4rvGjAYLjnGarT2kcq4dBj2p6EOJw4Klm9QMGkeYR4RuvXPtWvqWjMkv8Aoxx659KzBoM9xtKzBSw70JxT1YKEmQieNyVXoT3qQEh+cHIqnc6TqumkvLbtJH/eQZFQJf5+98vY+1auHWINNbmrndj1H60/dlgG571Uiu0K/L/Op1kD9Pl9KzsxEi4bPHelBUKffpTc8jHT2pQQDjGc0rAKB8vPB7U08nC804kBeTnBpXxnGNvpjvQA3bgnPamyThFGTz6UrAshVSBx+tLY2SkF7lufc0xMgaVjH+6TOT1NRG7ZGxMhGO4rTnuIFG1So28VnXF3A6lSwHFCve1hXDeGX5SCG/Sgg78p61kyXIRv3BOB60NqMmzAOCeta+yfQdzWyDgA4INDYDFmf8KxkncsuWIycmpTKxbMhzzxR7MDWDISNrDPfNIeMex6ispy+Ny9M1NBckEbjjFS6dkNGg2M8dutKACp29T0qGKZMYY53HipFbaxXof0rNoY/AxuHT0oXBzg44ppx0PBNLjPTqOM0ACAHoc/WnkE8Z9xTWA3ArwMc04n+LoAKtMBFHzZbvT+pA6kHNJnJwMYoBHbmqHYUnqOhznNO+9yTjHamLz053cc07q304NJjsKckZzyeOlGSeMdRk0ikg89AadnPTtx9akkNuMYpygjIf8AAUq85ppy2MHoetIaAckAd+tBx1/rT2IAyME54Ipi/dIPQUiheGXK8GilXI65xiigVjkck+5zUgUxW/nHhpPlT6etMiQyOscYyWOKLyUGUoh+SP5V/rXo7szIR97HYUH86UfKoJpM9x3qgLOm2pvL+KEdGbn6V6bZQqm0KOFAAA7VyPhewKA3DrkyDCe1d3Zx7U3YwcVx1pXY4q5aByox2pjLuUbPWnbsrgde5pA4Ax6ng1z7Go9Y88saNwHT8qQ5ZdpOKApHU80gA4L5fsOabkBTjmpOASDzkVG5UA7fSk3ZXHFXZSuMGNiahtYlBUH8KmuUJgIU9TyabEoXAGfpXm1Jts76cUiycrjtnrWbqGhabqSl5LZVb+8nBq6+7+Ic9jTAxUcevSpjVnB+6zWUIyWqOSvfBVxGxfTZxKMZ2McNWO7XdkxjuoXjYD+NcV6Pn5yScEdxUzW0F9CFuIllU8EMK7Y457TRyyw6ex5zDeo5+dtvtVg3QJBHQCtzWvA1pIHm06UwP1EZORmuSu7DUdNlKXETFRxuUZFdsJU6qvBnJOnKD2NE3CjknIPao5bvYTj0/KssXHQk/WmPcMThccnk1apkNaG0NQtowPMJxgFgvWs6/wBXkuWKxnZFngDqfrVBiWYknAzTDgn8a2jTSM7D2nY4yxP401n3c55ppXH9aAOf5VpZBYRjzQFz070EYU5pV4FMRIrE4P8Ad4p4Yv1qIY9OPSndeRx7VLQrtFuJwFK9iKiLgPkcU0n5fl7UiPuznoajlDmZbhk4B7j9avkh1BB7cisqJxgA5xnrVqGURrk8cnFYziWmXM5Az6Yp3YADHSqouU35NTiTeu9azs0USFix/wBnoaUNx1zxigfMce2aaAc4BHWquMf82eB6U7GCSDgUik8A9c04Eg4qbjADgHpzTj357UmflxinA4OT+VTcBQM4PYijb855wQOfeheSdx6HIoxuz6560xDgfTuKBwQAeaa3EfHrSgfdYfjT5dAF244z8pNPxtGD0pFGM8fLSkHAJHFSFxSBkUUoXcDj0opDOWgja1sXvCCCx8uIn+93P4CqGM8jpmtjxE8cWof2dbOHgsF8lWXozfxt+LZrJXvj1r0zMCcjHWp7O1a7vIreP7zn8qgJxnbXUeD7Eh5Lxx22xj+tROXLG7A6bTLEQqkYHyqMCt1CEQA464qhD8igg9ODT1nBPJ4FcTfMi9i10YgCnKgZcn8BUIkDAMp4qeEl1B6MPWpZYpwMY696TOcZ4pxcNkben60Ict6cVAw25OOhNQXBeCNJnhkFs/3Zth2t681NMwWFmPGBxXbaVPG3wlumO2aNLOZdhGdrZxkfmK48RNxsjpw8L6nndyVUKUOQxyDRENs2KRVQQQjG75Rijdsc8j3rjvc7USzbSwAPNQMAHG4EY703ziJQCNx7nNE77mwp6DJpdRi7sq2BkVbtXxAoP3h+tUd+LYP0yQKuMPKjz2Azj1ocQG6hcpDDukO3J/Gual8SWltdOZgZ1Kk4x0NV9c1BY5Cjy75GOSPSuVZg0mc5Ge9ephMKkuZnBWrO9ibVbyK9vGlihWH0C96zyxx/WnP97A5xS4GB6V66VlY4276kYORjFOTAb1Hag/e+XgUhwMelUQK7ZFN5+lLn5uecil25x9MUhCcZ5pCeSRS7SAM9KOOfQ0xBnHWlDZ6HkU3APHenlQj46ZFAEm4cnuBTARjIpQAVYZ7daiUgMOOlJILFgnI/CnMwKjB9hVfeT+dPUgEE+ualoETbyQM8VasZgH8v1zyaqMMqvPINJG4SXfznPNQ0mija6KMHpwDTwMbT79KZC3nxccHt7U9QTweuetc9rFoe3zA7Txnj604A8E9aTpnB4PT60qklORz0qWMcOjClHYeopAvRTwccEVIF445YcUgGqTtyeueaeQM4PX2oUAMQT0H50MAI1we/NFriEI+XnpQgJ+mOlOLAsAOvanoOx61SXcQxBjrzjtUmO2aXbgn0FKMdh70+VAJsNFSLljyMCilYLnBYLNyee9LjA+lOXoD+dNPTFegSiW0t2uryOFRy7DOPSvRLOBLaGONBxGu0Y9a5zwpp+Q97IvX5UJ/WuqjXA98cVxV53dhdSYOAp7ccimK/zHA4xUDt1yee5p0Rzis4bFN3L9sw2lO3Xmrscg2D+9WbbsFcbu5rTwGQEACnLQ0WwHJYEfjTwBhsdTxUec4x+FSAYUknHOc1mUVb9v3QRepGa6XRw8Hwd16ZicTSbI19t6ir2neA7HU/C0d/fyyw3ckMlzGFOAIwOMiq+mR3GofAXy7eP985MhJPVEkyTXl1Jqeq6Ox6dGDjE4oMVdR0VeDXYfDe2t72bWWuII7hVRFAcZ25Y1xUG2djtJJI6/rXTeC/EEGl+HvEVvjZdNGZonzgsfuqo/PNYyi3F2NFo9SPWLLTNU1z/im41tzArCeKR8BzngrXO3MEkDsZo3iO7aCw4J9M1JZxzF3ZUdjDHvkKjoOmfzplxNcSRiGSVmhWTzFRj0bpmqXYbsEybreJARjOaTUL1bXT55ZTh0T5fc1asjavMkVwhcBeCO1Z/i+K307ScxTrdJLnA7ofQ1pSXNUSM6jtG555c3D3ErSSHLMcmoS2FPb0pmcsSOuc/SlHK59DX0qiloeM5XInb5qA3zDHSnspOc8HrTQOeBVCugPT8adjtVmKxaRCfxp40+VhxExqOeIcrKi9BnjmgEcgDvVx9MmK7ipz6Cq8kEkfylTn1xQpRYuVkQzgg03uKl8ot1644pBDyM8VV0LcZwXx2pz/ADMe4HFDDazY/WiMnJ+lMQwnA4NN7UpGMjpQF96ZQsfBPNP3Egcjmo8A9Kfnnp0pMRMD+Jpdxx81IBwMUbs5BrMZbtblkkCE4WtYBTGD696wI8+YPXufStu1PmQoQe2CKwqKxSJVG7g9RUm35dynrQqYb5QKdsJ7YFYjEUEDGeRz9KkyF59uaaFIyOvr705QrMMjjHNAXHD5gPWkC7eAMn1NSKoK5A5xj6U4L6ngCqUrIQxU+UZ+tLgnGPxqVY14AP505YwG6cVSkBCFOSP0qXYcqAOtSqoDEnuKcCeMDkcU9AIwgC9M5oqYAcbuooqRHnmPlpYYHurmOGMZaRgopnQda6LwpZZlkvZBwAUjz3Pc12Slyq5KOntLdLa2jt4+UjUAN6+9TSthhgccYp0ZATBHNQyPkg5wOlccmnHzGMP3iHPvTlOF+XrUAfMpqTd8wzx9KzjoxFyBsupathgDGNprIt0yw9zWsicc9qqbNI3AL82QccVYs7RtR1O1sEBLXEqocemef0qFDnKgdjzXXfDjTTca5dX8gylnHsT/AH2/+t/OuPETUKbZ00Y80jT+I2syeGobFLDavnW0lqoPQLgCuT8I6xHpvgfXNJut/nC1eS2Rl4KsOcV2HxH8H6j4rNg+mSxqbVXDJJxuyQa5bWrm90y9a01LSsyCxW3SSFPkfPBya8uny8nu69T1YrWxxGnMI0+fjK8H3q74e0ga1r8dgS0SszF5VH3UAyTUF5C8TNJHayiEttVthwD6V0nh6CwKq2mXdxHq90jw7HT5FBGCDWrlpcVrux0k/hGDSbOS50S7a5tb9VjZMZ3jtg1gX3w8163+aK3W4iPI2Nyvsa9O8MWP2Tw3plrKVc28RQkexPNXzepHe/Z9+2RxwvrXF7WSk30Ka0PCTo99p7y/bLSSJuill7+1cD4o1bzc2cS4H8RPrX1rfxeZC2+JZGSNmUMM8gV8c+I5zNrM5ZFRi7EqB0OTXr5fadRt9DgxbtFJGMTgY6U5XHQelMYYbJpACK+h3PMLBUNHn+ICiCLfMgH3iaaqNwfUVa01Ct4p64PQ1nLRDitTpLGyAX5hWlHYgjp2ot48RAjqTV+FSz89OlePKTbud8YXMltOcszLwOmKcujrKoSRfrxXQQwbmx15q9HbJnp14Bpe0a2No0E9zjT4YSWUsqbFxwD3qjq+g/2fYm5A3KOPpXpkVtHuAwOKdPpkM8e2RFdSehFXGtJO7HLDRtoeLaZprX91HC/CsT81Lq+lnTbpYlB5Fem6j4VABmsovmTnavFZ11olvfKsshzOo5V+1dP1q0rnLLD2R53cadNb4Mq43KCKg8ojrmuw1RBHGIJUO9egx2rL+xjy9+RvJ4GK2jXutTndKxiCAjkd6QKVb3zmukj0SeWMuE4HIOMZrDu0NvdSRSLgg1pCpzuyJlBxVyNh3PHemA5P4UHse1CMCxz0qyCSEZdSDkj1rdsV2RLnPuKwYWHnD0zXTWrKbdSnPHPtWNUpE2wdRxQz4IIHy96THBHX8aUDMZ9T0rnGB78c9sUgG45PekCnucYpcqGAz7mgLEyNs68fSnE7v4qg3BdzZ9xTTIOqHBoFYuK+1cY57U9XXbg8EVQaQ8c801pXVjzk+gouUoml8pxz3pBKBx0yeaorJIxG1WI9gTU0drezEGC2mcZ67DU86Rapt9Cz5ihiAc/WirEHhnW7kgrZuB6scUVDxEF1NFQn2PNY43mmWNBlmOBXo2nWAtLKO3HRB+ZPWuW8I2Xn6p9pkXMVuCT7t2rvCqoOee/1r0KslexyWbK8hCJ0wR61UmcYAHPepZzknd3qDr/DxXI3qMjHI5qzHyMEfSodpbGccVaiAO30NAupoWUXy5atALkYbjjtUMAWNRkdqtLJnpjpSbubRG/6sFj93GP0r0TwFA+m6fNJcuscVyquATyW5/piuChtmvryC0UhfOcKxJ4Udz+VelzWE8TpGsa7EVVXaeqgdf0ryMwqbRR6OEhe7Za8Tyy2+lrqNpKSIUZWCng57/hWZcXbSLYvPIS72cTEH1OecVYFvcvb39pqEnlWszlbZCeXBQE/rmsvXNKvr+80m404DfBFGZ/mwDECwx+deWr7XPRjZbmk2qWsNt9nvBDvUjyoioy7EZFYcyQ32vR3aQrYKpBLIOT61l64AnxJ01H3BjEvHbuAf0rtfDljDe2t3LfxYKTtCqnsF7/jVyTjFamtqcY3aNzShG9nH5DBo0BUH8f/AK9Z2oy2iawTMRFNDgFnOMrjOR61paVHHaW5t434VifwrE1K1klkgiuil0End1LjlU6qM/U1nJ+6jms+Y6FWWSISocoY9w9xivjzxuqDxrqHlBVUyE4ToK+vtKnaeN2lVV8t2jwvTAFfHHi26+1eNNUm2qqtdPgKMAAHAr3cpjecn5Hn4zRWMhgM880wNzQ2ckdfSmKcHjmvoraHmWJg2GGOa09IhMt4rc4B59qz4Y13fN25rqdEsSEEzjAboPWuavLljY0pK7Ny3XhSeSOgrThG6MEDBzWfAoQgZOc1qxPHGo3uq89zXkO56cbWJ0jCnOfc1ZTlc9s9qrwTxzsdrA44471oRRABQwxzmo6m8WiWBO4HGKtoRtGSB7UyJMDHXNO8oovT8aZTJQSvzCqV1YwXLBmiAIOSw6mrCM2drDNSn0pSlYS1MWXTrZpNzwqx6cjoKgOkWQYsIF46DFbbRB+SOhqtImM+malykXyR7Gc8ChdoUflXCeJtGWS/WReAy4PHevRZyiLg8HGRXNakUbg9eta0arhK6OfEU4yjZHmUsbQyGJxzTB8q46GtLXEA1FlQ9gazyQWGBk45r3IvmjdnjNWdhAcKcfhW1pU7JEUcZ7g1R06y+1Xaxt3yTXTQ6TFEo8o4zxWVaS2KSsRBgy89hTGk2KAvJNXBYYXG75SaztScWRSMnMzruCjsK51d7FD/ADcZLNgnjBqeysLjUpttlE0vZnH3R+NHhPwxceJp5Lq7Zo7GA/Mw/wCWh9BXpcMENlai3tI1ijUYCqK5sViI0PdW51UsO5q72ONHhC8EJkmnjUK23aOTSp4bRQPNnZj6AYrrZoy0BdOueRVDhuX/AIRjHvXm/W5y3Ov6tCOxmW+gaYhBlR5G75atGKy0+3CmG2jA9xk1Gy7pAc4BHSllIRQAec8VEqs5dS404o0rYRhPlijAz/CtaEEuFwoVQOwrAgnkT5GI68VOsx5O7nvXJPnfU6IpI6Ce6MeNjZyOeaKwhL33Hn3orncTTmOU8P6UbHSoIWUCVx5kmfU9qvTkrnfV9EJJdh15rPvW3SZHFfXufNK585ayM+Vwzheopo3ZBzjml8orJnqDmjJ7UbmIigszY6ZqxGu1hjmq5cKOo55PNQR6vZpcbWnVRnG49KqOuwHUwnKLkVYQgMcdhVWBvNtklhdXjYZVlOcirQ+QEnt1qXobRV0b/hTT0vNQu5pslI49in0Y/wD1hXcM63G9TceV+6SNfYA1meDrV7TQIxLA2+YtOxxyfT9Ks3QErAvDIm0chRwa+XxU3Uqtnv0YKFNIrfEG9SHRNKeJ/MZbtQWQ9gOf0rbvFt4pba3tGIW4sJFjKn+Ec/8As1c9q2lWl9pMBmnkgit5mkZ2GBjbgircuuW2iabo7XcbSrOht4iBzuLd/wAKFqrLcbjaxy2uwX2i/EHQvt0qXBkRII5CvWPoc++TXbXtzYoYbae4NvIk54U9T15rn/inE0Op+GJduSt15efxU4qLxgx0vx950ybobiJGUkcZwQcVpVi5Qixwkm7HTwaPcXFwNSF0WRn3LscgYGcD8aJrfU2nsiI0SMuTd4bOBg4UfpS+G9Vi/sGBI0kdNzgMOgIPSrsjo6IBkDzN5P8AtVzyaUbC95yZTju5rVflV8M4Xbju3Ga+cPi74dfQfGHmnbtv088Bemc4NfSd7q8Gi6XdahdMGjgjO1D/ABseg/OvnH4g6pNrtwLzVDi52hY1HSNf7texlMmql+hx4uKdM4MZGB19TSxwmVjtxj+dH3e9JGD5o8s8549q+mex4ttdTU0zS91wPtWRHnp6muvjkRIuCFCjaBUOm3MbaK8NxbfvivDgd+xqtc21zPIsMKlUWPDP6tXm1W6ktTpg+XYWS9nlm2wnBxnPpURmmJBlLE9s9K7fw7YeDNW0mCw1d7nSNXz813ndG/19KpXdnptnf3dpFdJeW8MjJHOOkgx1FJQSVxOTbOcttWNnJuDfQVuW/jiLdGrx4OMbqq3lhpkgZIgBtH3l+tYFxpJikIhcNg9DTdOLHGrOJ6Zpmv2N02BJhzyue9bUN3FcEqGB6fn6V49p6XVrcqcEBa622vJZpk2EjjoPWuOpStqjupVr6M75IYwflGc1P9lXbyAah0yEvbI83XaKt3FxHDHncABXOjr3KUlsE6DqaqPbBs54xWJrvjE2QcW6qSp6muZm+It8seDFHICcHHGK0jSlLYxliIQdmdTq2Odg7YrmLzGx3YjCiof+EshvY+HIfuDVC+v0ltS6N17VoqLjI5atdS2OU1Ri140nU55+lVCpWVuPT8Kslle5Jk5Gcmr3hyz+3Xjlk3hTk57V7HNyQuzz7czNfTrBFWG4ClX2citcR5VRn8qkWLy1AUcf0qdYwVGK8+Um9Wbqm+pTu5I7CxlupBkRjKqf4m7VxVvFc6vq0cIJe6u5Ag9iT/IV0Hi6Zt1va/dUKZT7nt/WrPwt09b7xe1065WyiLD/AHm4H6ZrohJQpOY0ve5T0610u30XR7fTrQYjgXPTq3c1BIQkfPpV+9YncpPIOPrWfccpkn2xXyc5upNtnswioqyGIAYiehqNrZfMO3r3qeEcr34xVgxKCzCiOg2c/JCQzYU4B4NAtXmG58D61teXk4IxUPl7sgdc03OwJXM5bAs2c596sDTwSMmr+wIox6VAdytnqKyc2ylEemlqCGLcHrRVmMtt45J6UVk2yrM5yRwqjHTv9azbhgXbAq1dy4RVBHJrNZnPPFfWw3PnpaDX+ZMr2qpcuV4X7xqZ5MK3zcYrB1jUPKj2RP8AvWGPpWsU5OyMGyrrmqZkMFu3AGHZe9YJcsOT3qQ5bOeo6imEqTjpXfGKitBHR+D/ABC+m6olvcOTZzHawPRWPQ16Y0XnXcFuDtMkgUtnt3NeHk7cMp5B4r1cXZvNKs5xwzQK7HPtzXHjElG6Omhqz2SGW7S2WJXLRxKEBXHIFWF1a5QgTWvnLjAKjBFeJLdXir+7uJkVeDiQ1fTV9UgZfI1G4C8EZfNfNSw63uevGo5M9P8AEGu6XLpZs9QtJ9lxJsVU+9u7HFc7d2Vzq2j2Ok+ZmbS7wssrjBaLGQxH6fhWdb+JI76b/iaytayKAVmjj3EsK6ODWYbg/ak1S3abb5TO8OC2OefzrO84LQ3sQfEPVobyPTdOkLfa7a8gnjkxxJGT1rovEF1Yax/ol7BzGCIZe4bFef8AjKf7VLa3v2yGeUkArF/CARXYXIDXNwWtLiUM+UePDAgjtSqObpqw4xSdyx4clX7K2nWEDR/ZhukLnO4nqfxreYTLakyrH0yMelcvZX82lTTCGK6USDaS0Oc4HGfzq5D4mvpYl85ISucfPERWHL3G5O+hh+P/APkEwQNE6+bNnO7g7Rn+tePeJ7BrttqDIXvXq/jPVZdTtYElhSMQTEhkz82RjiuOS3X7LNduNwEh616uDk4PQxrR54WPJL22ktpCjj5hU+jWrXF6F7Z54qbWZjLqUsjf3+B6CtnwnbrtkmcZLnAB7V9FOpy0rnhxipTsdFY2KqMc4xWp9mUREgYNMtY8oBnpV5IdxA5ryudtneqaRiX1qXjGF+vvUug21opC30G8ISVz0rZNmXPTIoi05lDEcZ9quM7IhUdbnENFKmn3he3uBdM6m3ZPunn5s/hV21sHWxtLuZw3nBt8WPmj5wK654CExhTjpxVQ22z5mX5cVr7S6D2OpmXFmLaMPgMMcVZ8PXlrdXzICFaBDJKGGNqjqfel1COSWzMcHyjHQ1oeHtHjtYWklRWkk5JI5x6Vi56NM0hCzOtjvLZUgQzIjTJvjG77y9M1zWs6m9xNIIc+VH8px61Zv9Mt7uHEifdU7CDjZ34rktBGruRbwXUcsbuSVmAHHOefwrKEE9bmk5taEGpW0d1GEIyzc5rI/wCEUlfcY7hQcZANdPftcW2qXOnR28T3NvF5zDeMbMZPP0rFTVZL2wuL+CJhDAyiXaPuA9K6Yc8UcU4pvU5e/wBKutKy0ikgj7wHAqpFdkI6P1JwPau2mu4tQ0x0lwQR0/rXC3UP2eV8DjOQfWuynJT0e5yyjYqyNtZjnPNd94e0waZpqsx3S3OJH9h2FcXYWZvtUgtlGQ7jd7DvXpZRUAEfCKML7CjEStFRNKMOonvtwKegwuR35FNXBAOecVIq5YZ9K8+9zrSsch4umD646D/lnCigfUZrsfg7bhdO1O7wMyTBPyUn+tcH4jlMniG9YcAFV/JRXo/wnT/ilJWTIZrlyfyArbFvkwr+QUkpVDqLkF5CxzjOTVKY7h05rRVSY5OcsDn8KzpPmBxwa+U9D1ES2cYZgPerjx/uSBjBNUrJ9jYPRjjNXDISwxyKttk21IJl2NgelRKuM+varMoIUk/jUZ2qRuHOKh3KRE27aVHJI4pEhyq47dc1Ksm1sg4pjXDE7WHGeWHWkyx8YP8AD0zRVyGKLyWOfmAyBRWPMijzy+lAYDPIPpWNd3wtYWeVsKBxV7UXYkFW71zHiOdp5IrYcbufrX2lGPNKx8zUepVn8STEYiQDnIJrLMplkMkrZZzk1Xk+ViDwQcU3Jr01CKWhiaN5c2ht447SJgw5aQnrWcx3MT70CkqkrDHdetem6T8ui2cUgyVgAP8AOvM1OCO/Nel6VdLd6XbzldpcdB2xxXnZg2qaOvDJXZcXOCD3NTZ+Ve61EwJbg4FPjI6H0rwJdzvhoWI33Jt2gtnIJq7HPsA4AJ5I96zkOCCBx2qzGSfc5rJq51J6CSBZAwKgjuK3PDNxJ/ai2q3Mkf2gKqkscBsg/wBKxW+6e9OjkaKMTpw6EEDvwc/0pSWlh3NbW9WvE8R6gkF1NHtlKjDHjFNh17U4432XsmT03c4/zioNduEu9fluIipEyq5K+pUZqCLBxnhCcEj070WRRt3mpvrPhhRcXUb3ShneELg4U9fauYuZRFpUihvusfxrovDUNtLDrEmY0cxSQQeacbgwPNctMGKxqefl+YHvjiuinozOex5vqqD7U7Dufyrd0AlI1weQKr+JLHy9SVkTCSfdFX9GtyrICMcc17NSV6SPKjG0zrLJHkVWxx3rat4gcbc59azbLKKFAyOlbdvCdykNiuI74x0JY4l24HSlaNyMRLzmrsMS89KuRRBl4GKRfKYT6fIxHNVbizMCEPzk966khEHOKxdWvYi3kxJuc/pT5mPlRjLCud7DNa9goYdOtZqIxYK3JJ7dq6HTbcKAO+KVxcqRXulWK3fB5AzXLx26qpZVADNk8V1WqRYidV/irIs7V5l2pzg4PtTjoTUjcybvTLO+WRZ4ysjggupwSPTNZsNqNF0S9srflLpsuW6t7V0s9pJExDr0PUVm3lp5obd6cVuqllY55U0cTHAYo32cDuPQVkagIDOyrJuEaDgD+IjpXYy2nl7gPTJ4rjL3MF0Om9pPMP5YxXRQacmzgqRtobXg/TwtvLdtgtI3lhvQDrXShdzEDpmqelWH9naalvncxYux9c1eAw3J4rKrUvO50wjZAqYyB2GafESXXHXjNDcdOc0sP/HwueuRXO2bxVzzzWJBLrGoOBjNww/I16n8JFJ8JuQeBdMuPwFeT3vN9ek9fPc4/E1618HW3+Drof3Lw/qorox3+7P5GdH+Kzp3haKaZcnBNU7iHaA+MdvpWzqMZcqUPJ61QkiO0g9K+YuemijDxIAexq7IywKmR15NV1j2yn86mnffbSxOobeqgHuuDmk5JgSXOG3MBwQMVXm+4cjtip4G86wA/iK4+hqOQYj5H1+tQFii0bKpOegzipIWKkynBAGGz604Y5RvvGoG/dBIhzgZZvU0rGq2LJu0L8feAwT7UVmFjuO3qOv0opcgrnHzKXJYniuW8SQs7pNEvCdSK6knOcnn0qjdIhhcuMqASa+ypvkaZ8u9Xc4A9eTzSAZOBzU043TMyjgnjFMVSrivTvoSNwR2o6dauBFORjnqDSGDMecdTilzgVhgjgV6T4ctSfDdo7ZBYH+dc34f8LTa5OPLU+RDzMyjoK9Nh0p4ohFHayBY1ACBegxxXj5liYcqgtz0cHSd+ZmT9ncKR37VPHZHaGb0rZtdMvCyzxWLSbeobpWklnqWp2ZQ6ZFEd2FYcEGvBdU9PkSOcS3BcZXO0VKka7DyBXQxeCdSlkBkeKIng5PSrcfw/uXU7r6JSB2FZ86ZZzEVpE1vLI9yiFRwh6t9KrRAInzHA3da3tZ8OXvh/R5dQMkNxGjKhTb03HGa5X7QDAoYscZrWKurhojTSBSx2dM1IQqQYVepwazBcuIwFLVG91ctEEzjBzVJC5rF+WP5B6d8d6hdUSXBVjt4zVVZ7kuvmvhAecd6DcvJNIR0OeK1iuUzlNMzfE/lBLUGI7mc4f0pumQ7X4PWt6PQk13wbq+oNciOTSgsojI5cVk6VAdy56cGuxzXIjmaXPc6Kyj24HpzW1EQGU7aq2kChQB1IzV9FPl57jtWR1LRFyLaw9DmpHuPLyM5OKpeb5S9etBuoRgt1rRPQbJJHcoGfOCePasY4W6dpBkk8fStB7oGMnPBPSs+RhIDnr60mmybpDkvbf7QU+6+MbSOa6fQ/KmxuODjkmuRKJMvzLlh0fuKltdVltCY8H2PrRysTaZ1GqJG6sQcYrA024FpcMrfcZqp3mtTXKiPOCaZaRs5JkJY8ZqrCUr6HWT2yTR7sDkelcxqUHlZ7AnFb9nOzWwBOcdM1R1MK0R3detSr3BxOQuIiFbHXNeWahcfab6WY8B37elenavMYbedl4YpxXmX2BzgZ/CvTwrSTbPMrP3rHphfLDb02jH5UbuMHmsIa47LGBFxtAP4ClGtyBsGEY9c1yuDbNYzikbpJzjp6VLa8yKT2PSsaLW0J/eIRz1rUtLqK4KtCw6/lWTTW500+SS0Z5vdP/pV7u6mZz+teqfBZyfDuqp1K3SN/wCOf/WrzDU4hFruoxY+7O4/WvSfgHe2xvtf0O4wJLqyM1uzHHzIDn9G/SvQxUPaUGkcNKXJV1PSZMHuBz3qo2GBxzgZNMgvbRLq1+0XUIUOoYPIOfrWz4i13wyNJuI49UsUmUgp5cgzwelfJxoza2PWdRHOSxfMCD1PrTnXLDHXGPwqro/jDwpFqLnVb9GVYt0eASC2az7/AMc+GE1iZre7ke088EbUPTvirWDrPVRZPtY9zXtyImmibAAYsvvSNMhGT361ian498MSKj2Usx2Egjy+WqlJ480Hy/kM5Zh02dKf1Ov/ACsbrQ7nRttLqUI45qKVwYy/cVhf8J3oEYUr5+7Yyldnei18e6CkIVzMOxynSn9Tr2+FlKtDuaZTcoYIck9hRUKeP/DokQC4Ycg8x8CipWFxP8jIlXp30ZyBxu544rJ166+z6cwB5l+UfStGViOhAz1PpXJa7eeffFEcNGnAx619XSjzM8FmaQB9O1MPzOCtSZ4+lRqRvrtMtSeNS2euRUoY8AnOOajhORkcDNSR5Zmx+dZMV7HsPwKhM39u7iDEqxqRjvk166VJOdqZIxnAryr4CIxj8Q7eh8nv9a9YEfTkdK+SzJ/v2fQ4b+Eiu6dRj8AMVKi8cDtxSkc+tORsdK8s69GBViwweB696QcnnsOtSA8UxiTnHSrQrIxPFdvLc+DNUiVsYiEmPXac15Uu1oFPGMACvbJbb7XazW7f8to2j/MY/rXiMg8iSS3PWJ2TP0OK7KLbhYmSsOD4U5FIxwPl4Y1GjNjn1pxUls56+1bcrIeoSH5MLUaH5txGR3qUqe3X1pqRnad3y98ngVpG5k7Iu296LXwr4hixzeW8cY/7+D+lZWlSFGVWbJFQ3l3bzRG2t5lklz8yqc4AqtYStBJhjkhq6OSShaRDavdHoNrJlFPtWnGQV49MGsG0vIzAvritSO4Vlwp5pLU6Lqwt0CeEI4FUJbmEEKXCfU1Zlk8w4B69axb/AElZ5dwGTjitYpGUpPoaqPBIB5cq+/NTLFA3/LVQa5uKwaNsDhulaa203Bx8oGMnpTHGLe5rvYwm3Ko4LnuDUP8AZTND64HWqQeSFcrnpmq817dMMtJIAfSlqDjYhu7R0lx2UdanspzGCG5GKzptUMUu2T589c1Zt5Y5YSydRV7oyW509rMGtvl4GKoX8u4Zz2xik0xmNkXJ+XkVDckdT25qWjbm0OS8RudgU8bq5R4wJDjnr+FbWv3pl1Bk3Aqg61jbtxyvXvXZCNloePOd5Mcnyj5eSBipBGwjAPOajCN945wauJGW2/SqdkRdkaq23joOKmtmkhw6MRjsKnih3JjHWrttAu4DHaspNDi2noZd1oj6rcXl1bcXIiNwUPWQKMvj3AyfwrBtZGglE1vI8Un95GwcH3r0S1nbTL61v7dAz2sofaRw69GU+xBI/GuU8W6NFoPii5gtMmylxcWh9YZBlfy6fhW1Ko5Kxco8upkj5h87Mx92NJsXngEn1pQT2HsaNhJ+orS4ue4ZUHIA4P5UuM+4p6rnIPXFKsXA3dB1qbkcxGODkelOK/KBUmwDjHOaVkA+/wBPak2JyICOB39qae+atFQM46Comix976ihSJbKz8896KsGME/hxRV8yMrlnU7ySMPtcgEYNcqzdfrWzq8/7vaDk561h9a3w8bRuzaQ4yE96UNgg96jpy8HrXRYgmSQA49alEpDHHpVUHLD1qQMCQetS0hWPXPgh4p0rSG1Wz1S6S1lu2j8ln6MRnjP5V7nkGNZI2DoR1U5FfGG7BG3rXWeFfiTr3heQJb3DT2pPzW8x3KR3x6V42Oyv279pB6np4bFqEVGR9QnBJz60g9q4vT/AIteFrrw+dSnuGt5Y8CS0Iy+7/Z9RWDrHxv0iGxP9iWc010WwPOGFX614McuxTlblPRliKaV7nqgOemTVe61CysP+P28gt9w6SSAV84ax8UfFGsH5742sf8Actxt/WuTur+5vJDJd3MsznqzuSTXqUsm09+RySxqXwo+rrjxRoenwrcT6xaJHnhvMBz+Arw7VvFGl/br6eC4EokndkCjqM150ZjwuSR6HmmF2DYIrvpZXSp9bnLPGTkdLceMLrK/ZoVQf7XNUU8U6qkhZbogZyARWUxzt7U04ZgNvPeu+NGnFWSOZ1Zt7m/L4s1WduZVjwOiLjNUrvV9QuxtuLp3HXAOBVBT82enakeQZyBmnGnFPRIlzk+p0PhGMyTXJPOAAf1rcmjeCZGxx3xWb4LUfZbl/wCLeB+ldFNCJYiF64rysU/3zPSoq8C3ZS7ocbq0obpo8Lu5rkbO+eCdo37cCtZLzYyOx3etcyhZmvMjqIHL896vIofHpisWyuvN5HTtWxCd7Jg/NSZtGzGywoD84PXrVyxuRaMfMVJ4mHKt2qwtsrp84zVK9047vlOARxg0I2jJE87WErLtQRDHIrPvxbxD5XyM9KoS2sqzbQ7bfQ0jQuifNk9evaqJckzKntvPus4wM8Vq2dgflBGKZEgDh5KtG8WB9zHGBRcxcLamjLGkNqsMfQcmuf1zUUtLSR2bAA60uoa7HDCztIApHJJ6V5n4j8QyatKYoSVtlbgf3jW1CjKo9djnrVlGNkNF2L6UsTyzE81PFE27JGNprnEd42BzzXS6ZdC7tCOBIvXPeu6rT5FdHlLVlqJTsO/nJ6VaUEMMVEvqOOKsQISvpXK2apFqJNvtmp44yGyD9aai/KCTnipogXAxWDZtGKL0Ue6PHYf41n+LLX7X4WsbzJaTTpWtnOP+WLHK/kcj8a0IscLntUrW63lndWLHAuIGCg9Nw5H8qzhNwmmbyV42PNtuML0Pc0BCBmnkNj5hjjOD2oBymAO9elqec1ZiKepP4UnzZJ7Y5FLgbePXNOJP8PpSEAZiyEcdqlAGcN1B/OowDkADtTvqec0mAn3lIHPNAT5sk4xSjjt+ApwHrSENYgLyMnOM0U7btBx196KCTm7uRppiT9arHipm5X0I71EwHGPSvUiklYrfcSiiiqAXr04pRTaUHrSAXJ7UqnDYNNXrSgZ6mgCRGJzg4p+M55561EBjpTwcjpzSZaegu4nIGfWk5C4P50dh7ikznGegpCGleTupQcqSaCOTmgDC+lMBQVbAzSj7xyeKaPlIJ6jtTeufeixI92DcCmHOMGkzxRjK00FzsvCKkacxAI3uTmuvihAj5HUVzXhOInSI/XcciuthUMAoGePyr53FS/eyPaw0fc1OV1q2aK6EsY2884qOG4JGM5OOldDqFp5yFSOlc1NbPEzOoIXOBWlOSlEwqxakbmk6j5MoWTgEdzXYWdyhKPlR0rzNJmGDjBXpWrb6zMkaiQ7cHg1M4dSoVeXQ9XhlQpwQfpT3RXHPFcBYeJ/IkVXPyMR3rfOvROMxyZ9s1jJNHVGUX1NeW2iAycZzWdd7VU9AKgn1uFEIZwT9elYGo6+oRiGAGO/enGEpEupGJavtQjtlJyBXM3msfu3ld9sanGSaytU1vMfmSZxnhT3rmbu/nuj+8b93nIUV6FLC31Z59bEtuxa1XWJNRZkUkRZ4HriswNg+tCkZJ/KkxjkV6MYqKsjgcm9xep9qns7hreYNG2MfrUC88HigAckcEChpNWYlJpnbWcsd1arIhG4/eX0NWkBXGOeea47T797K4STdlTwRXaxMksUc0TBlYZBry61Nwd1sbxlcsRjKnBqdDtwcYPfFV0B2+9SBj+lcu5tG5oKVKjbUsbGOZG7BqqW598cVbKZj644z9aiWh0rVHGa5bG01i4jIwGcuPo3NZpycBa6LxVHuuI5eT+7AzXPlcsOvrXdTlzRucNVWkN4Dktxx2pQGGMdcdPWjYDnryetKoO3njFXczAdQaeo+bmmhCCQOR1FOGTz1GKTENx8vB5zxUmdy+ppowWwR9KcpJxnjBpFO1hDznI5Hailx1yO9FMjQ5ZhkE9M9BTOlObAOAaQn5MV6qGMPU0UUUwCgdaKKAHDrRik604/d5pANzxxUgbpmo+TTiD1oKuhx7jPNBIA+U00jaB70mPSkK4u7pSZO719qVuB1zTQxU8d6YDmwW6596bkmlzkdKM560CDpVmxs5L24EaLkDlvYVW612fh+xWHTRIV+aQEk+1Y16ipwubUafPI09Jja3twgONpxxXT2ZG1e4xWHbRhbdWz1OSK27MAhcdPavm6kryuz3KStoTzwCWFivGKwr2DDYZc5rogpwQOlV7i3BGWUHjj2qYSaeg6lNM5WSwEmdnpgj0qu1k6sOdwA6V0aW6jIYYyeSKnjs424A/Sur2rscHsm2cl5MuRlCfpTiLlYz5bSA9RjtXYx2ERPGMVcSwtIUyVBJ9qHWQ/YSOCEF8xIUSfP3PrUM2nNGhl1K5KxxjJ5rubhUXjAC9jXm/jDVVub77FA2YYfvEfxNXXhn7SVjCvHk6mJqF59qnLDiMHCr/WqpPApCc5yOtFeqkloef1ANz+FOz69MUzuee1KD8vPSmFh2ePrThjAwajx7dKcPXtSJY4j92c+vFbWj6+bCAQToZYgfl9qxc84PSm5x09amUVJWY02jtbXxRZTfK++Js9+la8NxHKAYZA4boQa8z3Z7Yq/pupS2MwaMn2HauSphY7xNFUdz0y2UHPpV1jzjqMYzWPo+pQ39ssqSDeRhkHY1rn7u4HC+9eZKLi7M9CMly6GV4gtzNpeV6ocn6VyRXLc8DODzXfyCN4zEed/ynI6CvNbyWex1Ce0nxujcj610YePNGyOfELW5bYABjnpSZ5z0zWcL91cAgFac2pYGAuQOldPspHKX+cnB5p2GIG3pWbHqSofnHBHanNqsRx8rY7gUeykFzRxzijoBn1wKqi+ikACHAHXPepPtKZwWBb0zUuDQXJnbajE9cYoqKWVfKHXBNFCQHMck0poOabXqDA0UUdqACjNAooAUU7OcA03GKKQhTxml+ppvNJQA8HPFGPmA7U1etO6NQAh9PSm9TSk0hpjFopKAOaAJrWIzXKRgE5YcCvSzEsWnoi8fIFAxXnNhN9nvUlPRT+Vel2Y/tC3hljO5eOleVmDkkj0MGrtospBjT0AGSBVzTGzGB3zirEtsqW4VeuKr6Wu24ZR2NeFzXPY5bG0IsxjHXNRNAZGIIPB/Orka7hyKsqqjrTQmjK/s7cen6U5bAgcdSe9ajOu3jr7UhfCginzNiUEZotGjzx3qOTO4KeR/Kr8821SG5z0rmte1uHT7dytwgYDpnJqqcZVHaKJqNQRj+LtcSytmtYJAZpBjjtXm0p+ZmPPOTU+oXzXd00rnLE1V8zPBGfU19Hh6KpQ8zwKs3OV2IWJA780n8Jx2p7YK8UzOK6TEM5HNHXntTe9KW7UwHg+9K3TjpUatipCfQ0mTYSjpSgndSsc89KQAdoPX9KFbBpo56mlRhuO7pigW5dsbyawn862ba461sxeLLpUPnxLKByecVz0W6SVUQHcw4rUt9CvZwAcRq45JPSsKkIP4jWLktjdj8bQFSstpIoPUhqxvEV/Z6tfQ3dpuWQxhZlYYyfWtnTvBVq3zX1y8zHoqcCt8+HNKWxktFtlRZBgSYyynsc/WuX22Hoy9035JzWp5e0nzYXoOKRTxg1LfWU+nX0lpdLsliODnuPWoedvA59K9DRq6OV9hSoZc4pFBzkjA9aVcDluRXU+DPDkPiG+ka4uFS3tiC8QPzyew9vf3pSkoK7FGLehs/DvwTa6qp1XxCrLpwysEAODO3TP0FZXijwTfaHqNy1nHJdacr/urhBk7T0yPXrXrG3bBFDEqxRW6BEjTooHap7Gc+YRndkYIYdRXl/W5c3N0O1UE1Y+fPtj+WofkA9aK9G+JXgGK1tW1/w/Fst8g3dsB/qz/fUf3aK76bhVjzROeVNxdmeT5zR060nWge9dRI4+3Sk7UnXvQOTQAdqKXb1owaACjtS0nakITNFFFMYCnHtTaUHmgBKKD1oHNAADinA80m3nijoKAJBgNXS+EvEbaNqAiuDutJDhwf4feuYH3ge1PBOfb0rOpGNSPLI0p1HTlzI95dBMA0eHjcAo4PDCq9nYkXUgHAPIPc1wPg7xm+kSrZ6ixlsWYYJ5MZ/wr1aERMomt3WRGGVZTkEGvl8ThpUJeTPoaFeNWPmTJGqKpJ7AUOcnjoKZLIvHcZ4xWPfeIdO0/d9pvYkYclc5NYwhOekUaTcY6yNpe/esjXPEFpotkZZznPCqO59K4/U/ieqZTSbbeQeJJen4CuM1XXL7WWV7+beFOVUDABr0qGXzveexw1cdCKtA2Nc8b3l/uS0zbxHng/Nj61ycs0krbndmJ7k5oYlh+lIV2rXtU6caatFHkSqyk7tje3FAJC4pOnuKBitjIOaU0D7w4pB3+tIBM0YyaD1pKAHAUo4600ehpQeaAH54yKbkmkOT1xSjjpSEKBjrThgp0701RnpTxwCvagQ6NjHIrKcEHPFben69LBhZ/nUHkjqBWGMdqehwM9c8VnOKluK7PRtI12xvm8uKYLIBnDcZrfA3LwcjvXjqDnIOCvQg4xXZ+C9Xmktbm1uHLiMhoyT0znI/QV5uJwseVyidtGtbRk3jTRvt1mdQgH+kW64fA++nT8xmp/DvgyyvPBltc6jEy3F1M8iODhgi4UfrmtnzFcENyuMEHuK2NLkS9jitQQBbR4UZ6jOcVzwxNRUuRdOps6cW7nDal8L7iNd2kXazDbkxS8Nn0qz8HrSKfxbqGm3pME8kGVUjByrfMtejnIcdiCKim8O2U2u22uQweRexAq7RcCUFSMkeuTnNarGOUHGYnQSaaOhufCkkFoTbOZGVcsT3rFFo6Xa4UqM8g10Nj4gvoEaG9C3EewhJgMMD7+tV4f31wHcZLHJry1N3Omy6FmCAAGOVFkR1KsjjIYHqp9jRWi0eIlYDnP6UVopSjsyXFPc+NKCaM4pM19WeUFOBOOKbS54oAXHrTgRimg+tLjpzSAD1ptONIelAhKKMYopjCiiigApR70lL0oAB1pQfWk60oxSEO9ulKBjp1puTilzjvQBKPX867Pwb4y/suFrDUXP2b70bnnYfSuJVtq8mjqxI49KyqU41I8sjWnVnTleJ2mt/EC7vWaHS/wDR4Bx5mPmb/CuPaUuSzszMTyxPJqMj5Rg8elAPHTmiNOEFaKCpWnN3bFzuBAHNBBYZpM4p27I9OKswbYhTC/jmkI/HNLuwR9KU4HU9aNRakTYwCKQfSnn5utNxxTKEzgcd6Pp0oPJpBzTGIaAcUGimAuaUHH402nNw3HSgBcYFKMd6bjvTj0GaQCjnvS/SmjjpTsY5zxUkscoBGT2607d6dKZ2OOlHpSELvIbPT2rofCkpWadCM5UMK51jk8DgCtHSLqXTp3u41LRoNrkds9P61FSN4tFLc7lbomUrnp6VYhvJbS5SdDgrzx3FZlsymJZCc7xnNTbsgc57V4/LyuzOqM2el6fcw6naQ3kPO9csP7rdxW9bxjylABzjpXmXhHVv7O1yK1uD/ol43lueyOfun8+K9OfMEjLzkHBrlnGzudsZJogkjO49x6U61KrJyelOd/lwRxUIP7zH61iyjoVbzbUY7UVBZNvt8ZoocrFJJnxuaKWp7CxuNS1CCysozJcXEixxoP4mJwBX154x7b8BvhJonjbRr/VvEKtNGsnkwxK2MHuf5V5j8RPDEfg/x5qOjQOZIYJP3ZPXaeRn8K+mvgN4B8T+BtMv49dkhWG62vFCjbijc5J/MV438Zfhp4s07XNU8U6oIrmxmnLmWN+UUthQR26gUAeSAcinkYOcVGOtSdeKQhrAg80meKUjJpDwaAA0lBopgFFFFAwpRSUCgBcUuPSkFKeKQgAz1NO7im0oycfWgB+McdRRjHIP503PX9KUHON3PFIB2Rt5HOKQ5OMelICCMZoBwOKRIhwMUUpxSH5e1MAoHvSA9aUc96Bhn2pD7UGgdDmgBpHFJilJoqhiE0GjFB60DF7ij1pQOKVVywpCuOxjrS5G8dxStzzSZ5BxUkD3XvjHNN4/WnZypxnHWmkcjFIA9aT+HilHBPfikznj0pjErb0kpdae1mwUKWJJxz7c1igVoaTL5Vxt/vDoaip8Og1ub2iTOFmsZzukt+mepFayqpbjkVy08zWmvR3HIDY3H1zXTh8bSO44rz68dpI2iEiF42Vmwe2D09K9c0DVRrfhu0vid023yp/+ui8H/GvJSSRjOfaus+HWoMs2o6ceVZFukXHQ/dY/yrlnG8TelKzsdvK+eF5qPJyPUdaSVzjjihXwoz+dcUkdqWhsaY7MrY6Zoqrp8uwsAeGPFFYy3LjsfJNSW1xNZ3UdxbSNFNEwdHU4KkdCKaPl5xS5G7nuK+zPEOnT4m+No12p4m1ID0Fw1U9U8b+J9as3tNW1u+u7eTG6OWYsp5z0+tYwIHB/OlIOf5UrgRgU7GAMmnE4zj6U0jDClcQ0d6Q8jpTieo9KZmmAUUUUxhRRRQAUUUUALRjNFOAxQIbS9qU0D86QhB1pSeaOvSikAAgdqdn5j2FMpc9aAHZFIck0nbiimIMc8d6QjHSl4BoPr60DE7Up4FN70MeaBiUuc0lApgLR3ooPNICRRQxHGKF+7ik9jSJH/e470n8QHoaUJuTI6g9adt+dSec0gADIJ7Z7UhXPv707bliM8ZoIx0PFIRHjA4oPAwKU+nQ0hpgKpwDTo3KurKcHNMH86VfUdqNwNHUZRJDbzd2HQdq6i2ffDGw6bR1+lcSTuiVT0Vs12VvlYowOflFclZWikaRkXRkkEdOefWtLwjcmy8ZWB3bVmjlgfnhgVyB+YFZS5IwOaZFL9n1Gxl7x3cZwPTcB/WuS19DVOzPXnlJlEWDkDk9qfkquM5phX9+3PBY49qRjjPc15zXQ9SL0LFpMRIOcdjRVeMNkt0orKUdS0f/Z";
        form.AddField("img", base64String);
		form.AddField("role", "sw_engineer");
        UnityWebRequest www = UnityWebRequest.Post("http://ar-divyata.us-west-1.elasticbeanstalk.com/postreq", form);

        www.SetRequestHeader("Accept", "application/json");
        www.uploadHandler.contentType = "application/json";
        www.chunkedTransfer = false;
        yield return www.SendWebRequest();
        if (www.isHttpError || www.isNetworkError)
        {
            Debug.Log(www.error);
            Debug.Log(www.responseCode);
            //print("Error: " + www.error + www.responseCode);
        }
        else
        {
            print("Request Response: " + www.downloadHandler.text);
            var response = JSON.Parse(www.downloadHandler.text);
            

            TotalScoreNeedleRotation.ShowScore(response["metrics"]["score"].AsFloat);
            float curExperience = response["metrics"]["experience"]["current"].AsFloat;
            float reqExperience = response["metrics"]["experience"]["required"].AsFloat;
            float matchingSkills = response["metrics"]["skills"]["matching"].AsFloat;
            float reqSkills = response["metrics"]["skills"]["required"].AsFloat;
            experienceMeter.fillAmount = curExperience / reqExperience;
            skillsMeter.fillAmount = matchingSkills / reqSkills;
            /*Response response = JsonConvert.DeserializeObject<Response>(www.downloadHandler.text);
            TotalScoreNeedleRotation.ShowScore(response.metrics.score);
            float curExperience = response.metrics.experience.current;
            float reqExperience = response.metrics.experience.required;
            float matchingSkills = response.metrics.skills.matching;
            float reqSkills = response.metrics.skills.required;
            experienceMeter.fillAmount = curExperience / reqExperience;
            skillsMeter.fillAmount = matchingSkills / reqSkills;*/


            //found = true;
            if (found == true)
            {
                resObject.SetActive(true);
                resObject.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 3.0f;

            }
        }

        StopCamera();

    }

    IEnumerator WaitForRequest(WWW www)
    {
        yield return www;
        if (www.error == null)
        {
            Debug.Log("WWW Ok!: " + www.text);
        }
        else
        {
            Debug.Log("WWW Error: " + www.error);
        }
    }
    /// <summary>
    /// Returns the contents of the specified file as a byte array.
    /// </summary>
    static byte[] GetImageAsByteArray(string imageFilePath)
    {
        FileStream fileStream = new FileStream(imageFilePath, FileMode.Open, FileAccess.Read);
        BinaryReader binaryReader = new BinaryReader(fileStream);
        return binaryReader.ReadBytes((int)fileStream.Length);
    }

    private void OnPhotoModeStopped(PhotoCapture.PhotoCaptureResult result)
    {
        capture.Dispose();
        capture = null;
        isReady = false;

        Info.text = "Camera off";
    }

}